with main;
  height=260;
  width=1095;
  with trackbar;
    left=44;
    top=29;
    width=928;
    height=40;
    enabledmode=0;
    caption="";
    identnames="kP";
    identvalues=[];
    maxvalue=100;
    minvalue=0;
    increment=0.1;
    incrementhotkey=" ";
    decrementhotkey=" ";
    eventmode=0;
  with label;
    alignment=0;
    wordwrap=false;
    left=990;
    top=35;
    width=11;
    height=13;
    enabledmode=0;
    caption="kP";
  with trackbar;
    left=41;
    top=80;
    width=929;
    height=40;
    enabledmode=0;
    caption="";
    identnames="kD";
    identvalues=[];
    maxvalue=0;
    minvalue=-100;
    increment=0.1;
    incrementhotkey=" ";
    decrementhotkey=" ";
    eventmode=0;
  with label;
    alignment=0;
    wordwrap=false;
    left=994;
    top=90;
    width=12;
    height=13;
    enabledmode=0;
    caption="kD";
with end;
