with main;
  height=260;
  width=666;
  with trackbar;
    left=20;
    top=30;
    width=619;
    height=40;
    enabledmode=0;
    caption="";
    identnames="hi1";
    identvalues=[];
    maxvalue=100000;
    minvalue=0;
    increment=1;
    incrementhotkey=" ";
    decrementhotkey=" ";
    eventmode=0;
  with trackbar;
    left=11;
    top=87;
    width=619;
    height=40;
    enabledmode=0;
    caption="";
    identnames="hi2";
    identvalues=[];
    maxvalue=0;
    minvalue=-10000;
    increment=0.1;
    incrementhotkey=" ";
    decrementhotkey=" ";
    eventmode=0;
with end;
